# Application configuration
application-name: gen_ai_training

client-openai-key: ${AZURE_OPEN_AI_KEY}
client-openai-endpoint: ${AZURE_OPEN_AI_ENDPOINT}
client-openai-deployment-name: Mixtral-8x7B-Instruct-v0.1
#client-openai-deployment-name: gpt-35-turbo
toolCallEnabled: false

embeddings.collection-name: some-collection
embeddings.deployment-name: text-embedding-3-small-1
embeddings.vector-size: 4
embeddings.search-limit: 2

